name: Build Civic Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
         dotnet-version: 7.0.x
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Decrypt Certificate File
      run: |
        echo "${{ secrets.CIVIC_WINDOWS_CERT }}" > cert.pfx.asc
        certutil -decode cert.pfx.asc cert.pfx
    - name: Add Cert to Store
      run: certutil -user -q -p ${{ secrets.CIVIC_WINDOWS_CERT_PASS }} -importpfx cert.pfx NoRoot
    - name: Build
      run: dotnet publish CivicMobile/CivicMobile.csproj -c Release -f:net7.0-windows10.0.19041.0 /p:GenerateAppxPackageOnBuild=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.CIVIC_WINDOWS_THUMB }}"      
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3.1.0
      with:
        path: .\**\AppPackages\**\*.*